application: fullcreditproject-148405
version: dev01
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: kaori.app

- url: /static
  static_dir: static
libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
